[package]
name = "luxafor_ui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.7.2"
luxafor_cmd_runner = { path = "../luxafor_cmd_runner" }

[build-dependencies]
slint-build = "1.7.2"
