[package]
name = "luxafor-ui"
version = "0.1.0"
edition = "2021"
description = "Luxafor-ui"
authors = ["Robin Kristiansen"]

[features]
default = []
slack_oauth = ["dep:hyper", "dep:hyper-util", "dep:http-body-util"]
slack_sync = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant, but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "luxafor_ui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
tauri-plugin-opener = "2"
tauri-plugin-store = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
luxafor = { version = "0.3.0", default-features = false, features = ["usb"] }
slack-morphism = { version = "2.10.0", features = ["hyper"], git = "https://github.com/nibrobb/slack-morphism-rust.git", branch = "add-oauth-user-scope" }
tracing = { version = "0.1.41", features = ["log", "log-always"] }
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
tokio = { version = "1.43.0", features = ["full", "tracing"] }
hyper = { version = "1.6.0", optional = true }
hyper-util = { version = "0.1.10", optional = true }
http-body-util = { version = "0.1.2", optional = true }
rvstruct = "0.3.2"

[dev-dependencies]
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }
tokio = { version = "1.43.0", features = ["full"] }
hyper = { version = "1.6.0", features = ["full"] }
