[package]
name = "luxafor-ui"
description = "Luxafor-ui Tauri app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []
slack_sync = ["dep:slack-morphism", "dep:tauri-plugin-opener", "dep:reqwest", "tokio/time"]
tracing = ["dep:tracing", "dep:tracing-subscriber"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant, but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "luxafor_ui_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = { version = "2", optional = true}
tauri-plugin-store = "2"
tauri-plugin-deep-link = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
luxafor = { version = "0.3.0", default-features = false, features = ["usb"] }

slack-morphism = { version = "2.22.0", features = ["hyper"], optional = true}
tracing = { version = "0.1.41", features = ["log", "log-always"], optional = true}
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"], optional = true}
reqwest = { version = "0.13.4", features = ["json"], optional = true}
tokio = { version = "1", optional = true }

[dev-dependencies]
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "fmt"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }
