name: Release DEB

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag to use for the release (must include the v prefix, e.g., v1.2.3)'
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
    secrets:
      GPG_SIGNING_KEY:
        required: true
      GPG_SIGNING_EMAIL:
        required: true

jobs:
  publish-deb:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout tag
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.tag }}

      - name: Configure PGP key
        shell: bash
        run: |
          base64 -di <<< "$GPG_SIGNING_KEY" | gpg --import
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: Release
        env:
          GPG_SIGNING_EMAIL: ${{ secrets.GPG_SIGNING_EMAIL }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          # Download release using tag
          gh release download         \
            ${{ inputs.tag }}         \
            --dir deb_repo            \
            --repo nibrobb/luxafor-ui \
            --pattern '*.deb'

          # Download existing files in debian repo
          gh release download         \
            debian                    \
            --dir deb_repo            \
            --repo nibrobb/luxafor-ui \
            --clobber                 \
            --pattern '*.deb'

          cd deb_repo
          # Scan for multiple packages and list them in Packages
          dpkg-scanpackages --multiversion ./ > Packages
          gzip -kf Packages

          # Create Release file
          cat <<EOF > Release
          Origin: luxafor-ui
          Label: nibrobb luxafor-ui
          Architectures: $(dpkg --print-architecture)
          Description: Graphical desktop application for controlling a Luxafor FLAG™
          Changelogs: https://github.com/nibrobb/luxafor-ui/releases/download/debian/Changelog
          EOF
          apt-ftparchive release ./ >> Release

          # Sign Release file
          gpg --default-key "$GPG_SIGNING_EMAIL" --yes --armor --detach-sign --sign -o Release.gpg Release
          gpg --default-key "$GPG_SIGNING_EMAIL" --yes --clearsign -o InRelease Release

          mkdir -v artifacts
          cp -v ../src-tauri/extra/debian/changelog.Debian artifacts/Changelog
          gzip -kfc artifacts/Changelog > artifacts/Changelog.gz
          cp -v                                       \
            ../debian/luxafor-ui-archive-keyring.asc  \
            ./*.deb                                   \
            Release                                   \
            Release.gpg                               \
            InRelease                                 \
            Packages                                  \
            Packages.gz                               \
            artifacts/
          
          # Upload artifacts to release with tag 'debian'
          gh release upload debian ./artifacts/* --clobber --repo nibrobb/luxafor-ui

