name: 'Build and release (self-hosted)'

on:
  push:
    branches:
      - tauri

jobs:
  build-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: ['Ubuntu-24.04', 'Windows-11']
        runner: ['self-hosted']
    
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install cargo-binstall
        run: cargo install cargo-binstall
        
      - name: Install binaries
        run: cargo binstall tauri-cli@2 trunk wasm-bindgen-cli
    
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'v__VERSION__-alpha'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: true
