name: Tauri build

on:
  push:
    branches: 
    - tauri

env:
  CARGO_TERM_COLOR: always

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: tauri-build
      uses: JonasKruckenberg/tauri-build@tauri-build-v1.5.11
