name: Tauri build

on:
  push:
    branches: [ "tauri" ]
  pull_request:
    branches: [ "tauri" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo tauri build --verbose
    - name: Run tests
      run: cargo test --verbose
