name: Build and publish bundles

on:
  workflow_dispatch:
    inputs:
      draft:
        type: boolean
        default: false
  push:
    branches:
      - release

jobs:
  Release-GitHub:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
          - platform: windows-latest
            rust_target: x86_64-pc-windows-msvc
          - platform: macos-26
            rust_target: aarch64-apple-darwin
          - platform: macos-26-intel
            rust_target: x86_64-apple-darwin
    outputs:
      app_version: ${{ steps.tauri-build.outputs.appVersion }}
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: lts/*

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2.9.1
        with:
          key: luxafor-ui-tauri-${{ matrix.platform }}-${{ matrix.rust_target }}
          shared-key: deps-tauri-${{ matrix.rust_target }}
          cache-on-failure: false
          cache-bin: false

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown, ${{ matrix.rust_target }}

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.16.2

      - name: Install binaries
        shell: bash
        run: cargo binstall -y tauri-cli@2 trunk wasm-bindgen-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        shell: bash
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y libwebkit2gtk-4.1-dev librsvg2-dev patchelf libudev-dev libayatana-appindicator3-dev

      - id: tauri-build
        name: Tauri build
        uses: tauri-apps/tauri-action@v0.6.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'Luxafor-ui v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          generateReleaseNotes: true
          releaseDraft: ${{ inputs.draft }}
          assetNamePattern: '[name]-[version]-${{ matrix.rust_target }}[ext]'
          args: '--target ${{ matrix.rust_target }}'


  call-Release-DEB:
    name: Release DEB
    permissions:
      contents: write
    needs: [Release-GitHub]
    uses: ./.github/workflows/release-deb.yaml
    with:
      tag: v${{ needs.Release-GitHub.outputs.app_version }}
