name: 'Build and publish bundles'

on:
  workflow_dispatch:
    inputs:
      runner:
        description: 'Choose runner'
        required: true
        default: 'github'
        type: choice
        options:
          - github
          - self-hosted
      include_macos:
        description: 'Include macOS in the build matrix'
        required: false
        default: false
        type: boolean

jobs:
  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: ${{ inputs.runner == 'github' && inputs.include_macos == 'true' && 'macos-latest' || 'self-hosted' }}
            args: '--target aarch64-apple-darwin'
          - platform: ${{ inputs.runner == 'github' && inputs.include_macos == 'true' && 'macos-latest' || 'self-hosted' }}
            args: '--target x86_64-apple-darwin'
          - platform: ${{ inputs.runner == 'github' && 'ubuntu-latest' || 'self-hosted' }}
            args: ''
          - platform: ${{ inputs.runner == 'github' && 'windows-latest' || 'self-hosted' }}
            args: ''
    
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Setup Rust and Cargo (Windows and Ubuntu)
        if: matrix.platform != 'macos-latest'
        uses: moonrepo/setup-rust@v1.2.1
        with:
          bins: tauri-cli@2,trunk,wasm-bindgen-cli
          cache-target: release
          channel: stable
          targets: wasm32-unknown-unknown
      
      - name: Setup Rust and Cargo (MacOS)
        if: matrix.platform == 'macos-latest'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown,aarch64-apple-darwin,x86_64-apple-darwin

      - name: Install Trunk-rs (MacOS)
        if: matrix.platform == 'macos-latest'
        run: cargo install trunk

      - name: Install wasm-bindgen (MacOS)
        if: matrix.platform == 'macos-latest'
        run: cargo install wasm-bindgen-cli

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libudev-dev
        
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'v__VERSION__-alpha'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: true
          args: ${{ matrix.args }}
