name: Run Rust tests
on:
  pull_request:
    branches:
      - tauri
  push:
    branches:
      - tauri

jobs:
  test:
    permissions:
      actions: write
    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-26.04
          - windows-latest
          - macos-26
          - macos-26-intel
        features:
          - slack_sync
          - tracing
          - slack_sync,tracing
          - default
        include:
          - platform: ubuntu-26.04
            rust_target: x86_64-unknown-linux-gnu
          - platform: windows-latest
            rust_target: x86_64-pc-windows-msvc
          - platform: macos-26
            rust_target: aarch64-apple-darwin
          - platform: macos-26-intel
            rust_target: x86_64-apple-darwin
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: lts/*

      - name: Cache Rust
        uses: Swatinem/rust-cache@v2.9.2
        with:
          key: luxafor-ui-tauri-${{ matrix.platform }}-${{ matrix.rust_target }}
          shared-key: deps-tauri-${{ matrix.rust_target }}
          cache-on-failure: false
          cache-bin: false

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown, ${{ matrix.rust_target }}
          components: clippy, rustfmt

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@v1.22.0

      - name: Install binaries
        run: cargo binstall -y tauri-cli@2 trunk wasm-bindgen-cli
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-26.04'
        shell: bash
        run: |
          sudo apt-get update
          DEBIAN_FRONTEND=noninteractive sudo apt-get install -y libwebkit2gtk-4.1-dev librsvg2-dev patchelf libudev-dev libayatana-appindicator3-dev

      - name: Check formatting
        working-directory: "${{ github.workspace }}/src-tauri"
        run: cargo fmt --all -- --check

      - name: Clippy
        working-directory: "${{ github.workspace }}/src-tauri"
        run: cargo clippy --all -- -D warnings

      - name: Run tests
        working-directory: "${{ github.workspace }}/src-tauri"
        run: cargo test --no-default-features --features ${{ matrix.features }} --target ${{ matrix.rust_target }}
